### PR TITLE
Added gen_selectpick

### PR DESCRIPTION
**Pull request by mfalesni**
Added function to pick N elements from M where M is usually greater than N.

Basically https://github.com/RedHatQE/cfme_tests/blob/master/utils/randomness.py#L41 replacement.

*I hope everything is correct*

### CODE REVIEW

**Comment by Ichimonji10** [comment]
The code itself is OK. (It could use some polish, but it is at least functional.) However, much like with #67, I want to take a moment to step back and think about design. In this library, we have [`gen_choice`](http://fauxfactory.readthedocs.org/en/latest/api.html#fauxfactory.gen_choice), which acts much like [`random.choice`](https://docs.python.org/3/library/random.html#random.choice). However, we have no methods that provide sampling of multiple items, either with or with out replacement. [`random.sample`](https://docs.python.org/3/library/random.html#random.sample) provides sampling without replacement, but there is no standard lib function that provides sampling with replacement.

So - I understand that this function is intended as a replacement for [`pick`](https://github.com/RedHatQE/cfme_tests/blob/master/utils/randomness.py#L41). But what's the more general problem being solved here?

* Is the goal sampling without replacement? If so, `random.sample` provides that already. There's a case to be made for adding `gen_sample` to fauxfactory.
* Is the goal is sampling with replacement? If so, a good solution might be a simple function like this: `def gen_choices(choices, n): return [random.choice(choices) for _ in range(n)]`
* If the goal is something even more exotic? Can you clearly outline that goal?

**Comment by mfalesni** [comment]
@Ichimonji10 hmm, it seems I overlooked this function, random.sample is basically what is required from it ...

**Comment by sthirugn** [comment]
@mfalesni is this PR still required?

**Comment by mfalesni** [comment]
@sthirugn Nope.

**Comment by sthirugn** [comment]
Thank you!

**Pull request closed without merging**
