### PR TITLE
Update travis.yml config

### PR DESCRIPTION
**Pull request by elyezer**
Migrate from legacy to container-based Travis infrastructure.

More info: http://docs.travis-ci.com/user/migrating-from-legacy/

### CODE REVIEW

**Comment by sthirugn** [comment]
ACK

**Comment by Ichimonji10** [comment]
ACK

**Comment by Ichimonji10** [comment]
But can't merge. :disappointed:

**Comment by elyezer** [comment]
@Ichimonji10 thanks for reviewing, @omaciel should merge it soon.

**Comment by omaciel** [comment]
ACK and merge

**Pull request merged**
