### PR TITLE
[RFR] Make fauxfactory play nice with static analysis.

### PR DESCRIPTION
**Pull request by jaryn**
Removing the dynamic imports tremendously helps with tools that do
static analysis of the code.

I believe the functionality stays unchanged.

### CODE REVIEW

**Comment by jaryn** [comment]
To get an idea of the importance of this compare these two screenshots. Over 200 false-positives eliminated.

Screenshot from 2020-10-02 00-27-13
Screenshot from 2020-10-02 00-36-56

**Comment by omaciel** [comment]
I'm not sure if your changes will have any performance impact, but I agree that the code looks cleaner. Let me see if @mshriver has any concerns before we merge and release.

**Comment by jaryn** [comment]
The performance difference seem to be negligible, if any. That is what I would expect.

I hope my metodics is good as it is tricky to measure module import time especially with timeit as it the `setup` is called once per several iterations and there is some caching behaviour of the modules importing that I couldn't get rid of. I think only the first result in *raw times* is what does matter.
```
(venv) ➜  fauxfactory git:(static_imports) ✗ git checkout origin/master -fq 
(venv) ➜  fauxfactory git:(079c17d) ✗ python -m timeit -v -n1 -r10 -s 'import sys;[sys.modules.pop(n) for n in list(sys.modules) if n.startswith("faux")]' 'import fauxfactory'
raw times: 17.5 msec, 1.6 msec, 1.48 msec, 1.56 msec, 1.52 msec, 1.61 msec, 2.4 msec, 1.73 msec, 1.54 msec, 1.61 msec

1 loop, best of 10: 1.48 msec per loop
:0: UserWarning: The test results are likely unreliable. The worst time (17.5 msec) was more than four times slower than the best time (1.48 msec).
(venv) ➜  fauxfactory git:(079c17d) ✗ python -m timeit -v -n1 -r10 -s 'import sys;[sys.modules.pop(n) for n in list(sys.modules) if n.startswith("faux")]' 'import fauxfactory'
raw times: 12.3 msec, 1.56 msec, 1.55 msec, 1.54 msec, 1.47 msec, 1.48 msec, 1.52 msec, 1.53 msec, 1.51 msec, 1.63 msec

1 loop, best of 10: 1.47 msec per loop
:0: UserWarning: The test results are likely unreliable. The worst time (12.3 msec) was more than four times slower than the best time (1.47 msec).
(venv) ➜  fauxfactory git:(079c17d) ✗ python -m timeit -v -n1 -r10 -s 'import sys;[sys.modules.pop(n) for n in list(sys.modules) if n.startswith("faux")]' 'import fauxfactory'
raw times: 12.3 msec, 1.66 msec, 1.55 msec, 1.58 msec, 1.46 msec, 1.45 msec, 1.5 msec, 1.5 msec, 1.48 msec, 1.56 msec

1 loop, best of 10: 1.45 msec per loop
:0: UserWarning: The test results are likely unreliable. The worst time (12.3 msec) was more than four times slower than the best time (1.45 msec).
(venv) ➜  fauxfactory git:(079c17d) ✗ python -m timeit -v -n1 -r10 -s 'import sys;[sys.modules.pop(n) for n in list(sys.modules) if n.startswith("faux")]' 'import fauxfactory'
raw times: 12.3 msec, 1.54 msec, 1.52 msec, 1.54 msec, 1.44 msec, 1.45 msec, 1.5 msec, 1.55 msec, 1.46 msec, 1.63 msec

1 loop, best of 10: 1.44 msec per loop
:0: UserWarning: The test results are likely unreliable. The worst time (12.3 msec) was more than four times slower than the best time (1.44 msec).
```
```
(venv) ➜  fauxfactory git:(079c17d) ✗ git checkout static_imports -fq
(venv) ➜  fauxfactory git:(static_imports) ✗ python -m timeit -v -n1 -r10 -s 'import sys;[sys.modules.pop(n) for n in list(sys.modules) if n.startswith("faux")]' 'import fauxfactory'
raw times: 18.9 msec, 1.49 msec, 1.38 msec, 1.47 msec, 1.41 msec, 1.38 msec, 1.41 msec, 1.45 msec, 1.37 msec, 1.46 msec

1 loop, best of 10: 1.37 msec per loop
:0: UserWarning: The test results are likely unreliable. The worst time (18.9 msec) was more than four times slower than the best time (1.37 msec).
(venv) ➜  fauxfactory git:(static_imports) ✗ python -m timeit -v -n1 -r10 -s 'import sys;[sys.modules.pop(n) for n in list(sys.modules) if n.startswith("faux")]' 'import fauxfactory'
raw times: 12.1 msec, 1.45 msec, 1.43 msec, 1.44 msec, 1.39 msec, 1.35 msec, 1.44 msec, 1.38 msec, 1.43 msec, 1.54 msec

1 loop, best of 10: 1.35 msec per loop
:0: UserWarning: The test results are likely unreliable. The worst time (12.1 msec) was more than four times slower than the best time (1.35 msec).
(venv) ➜  fauxfactory git:(static_imports) ✗ python -m timeit -v -n1 -r10 -s 'import sys;[sys.modules.pop(n) for n in list(sys.modules) if n.startswith("faux")]' 'import fauxfactory'
raw times: 13.2 msec, 1.45 msec, 1.48 msec, 1.46 msec, 1.36 msec, 1.41 msec, 1.44 msec, 1.44 msec, 1.37 msec, 1.48 msec

1 loop, best of 10: 1.36 msec per loop
:0: UserWarning: The test results are likely unreliable. The worst time (13.2 msec) was more than four times slower than the best time (1.36 msec).
(venv) ➜  fauxfactory git:(static_imports) ✗ python -m timeit -v -n1 -r10 -s 'import sys;[sys.modules.pop(n) for n in list(sys.modules) if n.startswith("faux")]' 'import fauxfactory'
raw times: 12.2 msec, 1.58 msec, 1.58 msec, 1.47 msec, 1.4 msec, 1.37 msec, 1.44 msec, 1.44 msec, 1.44 msec, 1.46 msec

1 loop, best of 10: 1.37 msec per loop
:0: UserWarning: The test results are likely unreliable. The worst time (12.2 msec) was more than four times slower than the best time (1.37 msec).
```

**Comment by mshriver** [comment]
Unit tests are passing and the change looks good to me, but travis isn't reporting back for the checks on this PR.  I'm guessing its due to the legacy integration events being turned off:
https://blog.travis-ci.com/2019-01-31-github-services-integration-deprecation

The travis build is triggered, but its result event is not posted back to the PR.

@jaryn check out the flake failure that results from __all__ being a list:
https://travis-ci.org/github/omaciel/fauxfactory/jobs/732102804#L838

**Comment by jaryn** [comment]
Well, flake8 doesn't like the star imports. I am not sure what can be done about that except of manually stating all of them.

To make sure all of them are really imported at the top level and nothing is left out perhaps when adding a function and forgetting adding an import I can prepare a test for this.

**Comment by jaryn** [comment]
flake8 doesn't like star imports. Neither do I, but it is better than we have currently implemented.

I made test.py:
```
from fauxfactory import gen_string

print(gen_string())
```
and checked flake8 and pylint's behaviour:

 * flake8 is not complaining with or without about using something that was star-imported. It seem to be expecting everything is importable.

 * Pylint does seem to be checking existence of the name in the module being imported. It is able to resolve what was star imported in it. It is no able to make sense of the `module.__dict__` modifications being done without this PR and complains about the name not being present in fauxfactory

Current behaviour:
```
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:1:0: E0611: No name 'gen_string' in module 'fauxfactory' (no-name-in-module)
```

With my PR:
```
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:3:6: E1120: No value for argument 'str_type' in function call (no-value-for-parameter)
```

I think this PR is not gonna make life of programmer without the "smarter tools" easier as the information what symbol was imported from where is not explicit. But it will make life easier for those who do use them.

**Comment by omaciel** [comment]
@mshriver are you okay with merging it?

**Comment by mshriver** [comment]
@omaciel @jaryn The flake failure in travis has still not been resolved. F401/F403 would need to be ignored.

**Comment by omaciel** [comment]
@mshriver friendly nudge :)

**Review by mshriver — APPROVED** [review]
Looks solid to me, and is passing CI checks. Use within SatelliteQE/Robottelo appears unaffected, functionally.  @jaryn Please keep an eye for issues once this has been released, should it impact any users negatively. Thanks for updating the library and improving static analysis support!

**Pull request merged**
